
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: trustfinance-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1q2w3e4r@#$"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '1q2w3e4r@#$'"]
      interval: 10s
      retries: 5

volumes:
  sqlserver_data:
